apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: bryguan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis-container
        image: redis:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6379